sudo: true
dist: xenial
services:
  - docker

before_install:
  - docker build -t bionitio-cpp .

script:
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-java
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-java -p bionitio -d /bionitio/functional_tests/test_data -v
