sudo: true
dist: trusty

language: java 

before_install:
  - ./.travis/install-dependencies.sh  

script:
  - ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/bionitio-java -d functional_tests/test_data
  - ./.travis/unit-test.sh
